import { normalizeBundle, type Bundle, type Recipe } from './schema'
const cooking = [
 ['saute','Sauté aromatics', 'Stir over medium heat until softened and fragrant.', 'Aromatics soften without scorching.'],
 ['simmer','Simmer gently','Maintain a gentle simmer, checking liquid periodically.','Sauce thickens and vegetables become tender.'],
 ['blend','Blend sauce','Blend the cooked sauce in small batches according to your appliance instructions.','Sauce is smooth with no visible pieces.'],
 ['finish','Fold together and finish','Fold the prepared component into the sauce and heat gently.','Sauce coats each piece and the dish is hot throughout.'],
 ['marinate','Marinate paneer','Coat paneer in yogurt and spices, then refrigerate.','Paneer is evenly coated.'],
 ['rest','Rest in the refrigerator','Keep the covered marinated paneer refrigerated.','Marinade has rested for the authored lead time.'],
 ['bake','Bake paneer tikka','Bake at 220°C on a lined tray, turning halfway.','Edges are lightly charred and the center is hot.'],
 ['fry','Pan-fry paneer tikka','Cook in a lightly oiled pan, turning to brown all sides.','Golden surfaces with a tender center.'],
].map(([key,name,method,cue])=>({technique_id:'tech_'+key,name,skill_tag:'beginner' as const,generic_steps:[method],doneness_signal:cue,common_failure:'Scorching or drying out',recovery_action:'Reduce heat and check moisture before continuing.',region_variants:['North Indian']}))
const ingredient=(ingredient_id:string,qty:number,unit:string,extra:object={})=>({ingredient_id,item:ingredient_id,qty,unit,scaling_role:'linear_to_anchor' as const,...extra})
const step=(step_id:string,tech:string,duration_min:number,attention_type:'active'|'passive',depends_on:string[],equipment:string[],uses:[string,number,string][])=>({step_id,technique_id:'tech_'+tech,duration_min,attention_type,depends_on,equipment,qty_used:uses.map(([ingredient_id,qty,unit])=>({ingredient_id,qty,unit}))})
const base={region:'North Indian',festival_tag:null,health_tags:['vegetarian'],cost_tag:'medium' as const,servings:4,substitution_links:[]}
const tikkaIngredients=[ingredient('ing_paneer',400,'g',{scaling_role:'anchor'}),ingredient('ing_yogurt',80,'g'),ingredient('ing_spice',8,'g'),ingredient('ing_oil',10,'ml')]
const recipes:Recipe[]=[
 {...base,recipe_id:'rcp_makhani',name:'Paneer Tikka Makhani',description:'Golden paneer tikka folded into a smooth tomato and butter sauce.',serve_with:'Steamed basmati rice or Indian bread',equipment:['eq_pan','eq_blender'],ingredients:[ingredient('ing_tikka',400,'g',{scaling_role:'anchor',default_recipe_id:'rcp_tikka_baked'}),ingredient('ing_tomato',500,'g',{prep_technique_id:'prep_chop'}),ingredient('ing_butter',60,'g'),ingredient('ing_cream',60,'ml'),ingredient('ing_spice',8,'g'),ingredient('ing_salt',1,'tsp',{scaling_role:'to_taste'})],steps:[step('s_saute','saute',5,'active',[],['eq_pan'],[['ing_butter',40,'g'],['ing_tomato',500,'g'],['ing_spice',8,'g']]),step('s_simmer','simmer',12,'passive',['s_saute'],['eq_pan'],[]),step('s_blend','blend',4,'active',['s_simmer'],['eq_blender'],[]),{...step('s_finish','finish',5,'active',['s_blend'],['eq_pan'],[['ing_tikka',400,'g'],['ing_butter',20,'g'],['ing_cream',60,'ml'],['ing_salt',1,'tsp']]),sensory_test_id:'test_coat'}]},
 {...base,recipe_id:'rcp_tikka_baked',name:'Refrigerated marinade + baked tikka',description:'A longer marinade, followed by oven baking for charred edges.',output:{ingredient_id:'ing_tikka',qty:400,unit:'g'},equipment:['eq_bowl','eq_oven'],ingredients:tikkaIngredients,steps:[step('s_coat','marinate',5,'active',[],['eq_bowl'],[['ing_paneer',400,'g'],['ing_yogurt',80,'g'],['ing_spice',8,'g'],['ing_oil',10,'ml']]),step('s_rest','rest',120,'passive',['s_coat'],['eq_bowl'],[]),step('s_bake','bake',20,'passive',['s_rest'],['eq_oven'],[])]},
 {...base,recipe_id:'rcp_tikka_quick',name:'Quick pan-fried tikka',description:'Skip the long marinade; a softer spice flavor with browned pan-fried surfaces.',output:{ingredient_id:'ing_tikka',qty:400,unit:'g'},equipment:['eq_bowl','eq_tikka_pan'],ingredients:tikkaIngredients,steps:[step('s_coat','marinate',5,'active',[],['eq_bowl'],[['ing_paneer',400,'g'],['ing_yogurt',80,'g'],['ing_spice',8,'g'],['ing_oil',10,'ml']]),step('s_fry','fry',12,'active',['s_coat'],['eq_tikka_pan'],[])]},
]
export const LOCAL_BUNDLE:Bundle=normalizeBundle({version:'1.3',root_recipe_id:'rcp_makhani',recipes,cooking,prep:[{technique_id:'prep_chop',name:'Roughly chop',skill_tag:'beginner',method:'Cut into similarly sized pieces on a stable chopping board.'}],sensory:[{test_id:'test_coat',name:'Spoon-coat test',skill_tag:'beginner',method:'The sauce leaves an even coating on the back of a spoon.'}],equipment:[{equipment_id:'eq_pan',name:'Sauce pan',method:'Use steady medium heat.'},{equipment_id:'eq_blender',name:'Blender',method:'Follow the manufacturer’s hot-liquid capacity and venting instructions.',safety_precheck:'Confirm your blender is rated for hot liquids and you know its fill limit and venting procedure. Otherwise cool the sauce before blending.'},{equipment_id:'eq_bowl',name:'Covered bowl + refrigerator',method:'Keep the marinade refrigerated.'},{equipment_id:'eq_oven',name:'Oven + tray',method:'Preheat to 220°C; use oven gloves.'},{equipment_id:'eq_tikka_pan',name:'Separate tikka frying pan',method:'Use medium heat.'}],identities:[['ing_tikka','paneer tikka'],['ing_paneer','paneer'],['ing_yogurt','plain yogurt'],['ing_oil','cooking oil'],['ing_tomato','tomato'],['ing_butter','butter'],['ing_cream','cream'],['ing_spice','butter chicken spice blend'],['ing_salt','salt']].map(([ingredient_id,canonical_name])=>({ingredient_id,canonical_name,synonyms:[],category:ingredient_id==='ing_tikka'?'prepared protein component':'ingredient',common_substitutes:[],produced_by:ingredient_id==='ing_tikka'?['rcp_tikka_baked','rcp_tikka_quick']:[]}))})
