'use client'
import { useEffect, useMemo, useState } from 'react'
import { normalizeBundle, recipeSkill, type Bundle } from '@/lib/moaka/schema'
import { canStart, criticalPath, estimatedElapsed, execution, transition, restoreSession, type Choices, type Instance } from '@/lib/moaka/engine'
const panel='rounded-2xl border border-[#ded9cf] bg-white p-5'
const button='rounded-xl bg-[#24131a] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40'
const amount=(n:number)=>Number(n.toFixed(2)).toString()
export function MoakaStudio({userId,initialBundle}:{userId:string;initialBundle?:Bundle}) {
 const [bundle,setBundle]=useState<Bundle|null>(initialBundle||null),[view,setView]=useState<'discover'|'review'|'cook'>('discover')
 const [query,setQuery]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('Describe a dish to load a validated recipe bundle.')
 const [servings,setServings]=useState(4),[choices,setChoices]=useState<Choices>({ing_tikka:'rcp_tikka_baked'}),[checks,setChecks]=useState<Record<string,boolean>>({})
 const [budget,setBudget]=useState(45),[scheduled,setScheduled]=useState(''),[instance,setInstance]=useState<Instance|null>(null),[loaded,setLoaded]=useState(false)
 const storageKey='moaka-studio-v13:'+userId
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw&&!initialBundle){const saved=JSON.parse(raw);const validated=normalizeBundle(saved.bundle);const restored=restoreSession(saved,validated);setBundle(validated);setChoices(restored.choices);setServings(restored.servings);setInstance(restored.instance);setView('cook')}}catch{setNotice('Saved session could not be restored. Start a new review.')}setLoaded(true)},[storageKey,initialBundle])
 useEffect(()=>{if(loaded&&instance){try{localStorage.setItem(storageKey,JSON.stringify({bundle,choices,servings,instance}))}catch{setNotice('Browser storage unavailable. Keep this tab open to retain progress.')}}},[bundle,choices,servings,instance,loaded,storageKey])
 if(!bundle) return <div className="space-y-5 pb-8"><div className="rounded-3xl bg-[#24131a] p-6 text-white"><p className="text-xs uppercase tracking-[0.2em] text-[#ff8a57]">MOAKA Studio / 1.3</p><h1 className="mt-2 font-serif text-3xl">A little planning. A calmer kitchen.</h1><p className="mt-2 text-sm text-white/70">Choose your components, gather what you need, and cook one ready action at a time.</p></div><p className="text-sm text-[#736e65]" role="status">{notice}</p><form className={panel+' flex gap-2'} onSubmit={e=>{e.preventDefault();suggest()}}><input aria-label="Dish or food preference" className="min-w-0 flex-1 rounded-lg border p-2" maxLength={500} value={query} onChange={e=>setQuery(e.target.value)} placeholder="What would you like to cook?"/><button className={button} disabled={busy||!query.trim()}>{busy?'Thinking…':'Suggest recipe'}</button></form></div>
 const recipe=bundle.recipes.find(r=>r.recipe_id===bundle.root_recipe_id)!
 const plan=useMemo(()=>execution(bundle,choices,servings),[bundle,choices,servings])
 const critical=criticalPath(plan.steps),elapsed=estimatedElapsed(plan.steps),eligible=elapsed<=budget
 const equipment=bundle.equipment.filter(e=>plan.steps.some(s=>s.equipment.includes(e.equipment_id)))
 const safe=equipment.filter(e=>e.safety_precheck).every(e=>checks[e.equipment_id])
 const complete=instance&&plan.steps.every(s=>instance.step_state[s.step_id]?.done)
 const pending=criticalPath(plan.steps,instance?Object.keys(instance.step_state).filter(k=>instance.step_state[k].done):[])
 async function suggest(){setBusy(true);try{const res=await fetch('/api/moaka/suggest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const data=await res.json();if(!res.ok)throw Error(data.error);const next=normalizeBundle(data.bundle);setBundle(next);setServings(next.recipes.find(r=>r.recipe_id===next.root_recipe_id)!.servings);setChoices(Object.fromEntries(next.recipes.flatMap(r=>r.ingredients.filter(i=>i.default_recipe_id).map(i=>[i.ingredient_id,i.default_recipe_id!]))));setChecks({});setNotice(data.message);setView('discover')}catch(e){setNotice(e instanceof Error?e.message:'Suggestion failed.')}finally{setBusy(false)}}
 function begin(){if(!safe||(!eligible&&!scheduled))return;setInstance({id:crypto.randomUUID(),recipe_id:recipe.recipe_id,scheduled_for:scheduled?new Date(scheduled).toISOString():new Date().toISOString(),entry_mode:eligible?'impromptu':'planned',step_state:{}});setView('cook')}
 return <div className="space-y-5 pb-8">
 <div className="rounded-3xl bg-[#24131a] p-6 text-white"><p className="text-xs uppercase tracking-[0.2em] text-[#ff8a57]">MOAKA Studio / 1.3</p><h1 className="mt-2 font-serif text-3xl">A little planning. A calmer kitchen.</h1><p className="mt-2 text-sm text-white/70">Choose your components, gather what you need, and cook one ready action at a time.</p></div>
 <div className="flex gap-2" role="tablist" aria-label="Recipe stages">{(['discover','review','cook'] as const).map((v,i)=><button role="tab" aria-selected={view===v} disabled={v==='cook'&&!instance} className={'rounded-full px-4 py-2 text-sm '+(view===v?'bg-[#f4510b] text-white':'bg-white')} key={v} onClick={()=>setView(v)}>{i+1}. {v==='discover'?'Decide':v==='review'?'Mise-en-Place':'Cook Mode'}</button>)}</div>
 <p className="text-sm text-[#736e65]" role="status">{notice}</p>
 {view==='discover'&&<><form className={panel+' flex gap-2'} onSubmit={e=>{e.preventDefault();suggest()}}><input aria-label="Dish or food preference" className="min-w-0 flex-1 rounded-lg border p-2" maxLength={500} value={query} onChange={e=>setQuery(e.target.value)} placeholder="What would you like to cook?"/><button className={button} disabled={busy||!query.trim()||!!instance}>{busy?'Thinking…':'Suggest recipe'}</button></form><article className={panel}><p className="text-xs uppercase tracking-widest text-[#f4510b]">{recipe.region} · {recipeSkill(bundle,recipe)} · {recipe.cost_tag} cost</p><h2 className="mt-2 font-serif text-3xl">{recipe.name}</h2><p className="my-3">{recipe.description}</p><p className="font-semibold">{elapsed} min estimated elapsed · {eligible?'Fits your time window':'Needs lead time'}</p><p className="mt-1 text-sm text-[#736e65]">Includes one cook and equipment availability. Timing and doneness still vary.</p><div className="my-4 flex flex-wrap gap-4"><label>People <input disabled={!!instance} type="number" min={1} max={20} value={servings} onChange={e=>{setServings(Math.max(1,Math.min(20,Number(e.target.value)||1)));setChecks({})}} className="ml-2 w-16 rounded border p-1"/></label><label>Time available <input type="number" min={1} max={10080} value={budget} onChange={e=>setBudget(Math.max(1,Number(e.target.value)||1))} className="ml-2 w-20 rounded border p-1"/> min</label></div><button className={button} onClick={()=>setView('review')}>Review ingredients & equipment →</button></article></>}
 {view==='review'&&<><section className={panel}><h2 className="font-serif text-2xl">Make it your way</h2><p className="my-2 text-sm text-[#736e65]">Buying is the default for ingredients without an authored producer. Ready Stock means you already have the full required quantity, ready to use.</p>{bundle.identities.filter(i=>i.produced_by.length&&plan.steps.some(s=>bundle.recipes.find(r=>r.recipe_id===s.recipe_id)!.ingredients.some(x=>x.ingredient_id===i.ingredient_id))).map(i=><div key={i.ingredient_id} className="my-4"><label className="block font-semibold">{i.canonical_name}<select disabled={!!instance} className="mt-1 block w-full rounded-lg border p-2 font-normal" value={choices[i.ingredient_id]||'buy'} onChange={e=>{setChoices({...choices,[i.ingredient_id]:e.target.value});setChecks({})}}><option value="buy">Buy prepared</option><option value="stock">Use Ready Stock — full quantity available</option>{i.produced_by.map(id=><option key={id} value={id}>{bundle.recipes.find(r=>r.recipe_id===id)!.name}</option>)}</select></label>{!['buy','stock'].includes(choices[i.ingredient_id]||'buy')&&<p className="mt-1 text-sm">{bundle.recipes.find(r=>r.recipe_id===choices[i.ingredient_id])?.description}</p>}</div>)}<p className={'mt-3 font-semibold '+(eligible?'text-green-800':'text-amber-800')}>{elapsed} min estimated · {eligible?'Impromptu eligible':'Plan ahead or explicitly choose a quicker variant / Ready Stock'}</p></section>
 <section className={panel}><h2 className="font-serif text-2xl">Gather & prepare</h2><div className="mt-3 divide-y">{plan.gather.map(({key,recipe:r,line:i})=><div key={key} className="py-3"><div className="flex justify-between gap-3"><span className="font-semibold">{i.item}</span><span>{i.gather_approximate?'≈ ':''}{amount(i.gather_qty||i.qty)} {i.gather_unit||i.unit}</span></div><p className="text-xs text-[#736e65]">{r} · {i.scaling_role.replaceAll('_',' ')}{i.scaling_role==='to_taste'?' · starting point; adjust to taste':''}</p>{i.recipe_qty&&<p className="text-sm">After prep: {amount(i.recipe_qty)} {i.recipe_unit}</p>}{i.prep_technique_id&&<details className="mt-1 text-sm"><summary>{bundle.prep.find(p=>p.technique_id===i.prep_technique_id)!.name}</summary>{bundle.prep.find(p=>p.technique_id===i.prep_technique_id)!.method}</details>}</div>)}</div>{recipe.serve_with&&<p className="mt-3 text-sm">Serve with: {recipe.serve_with}</p>}</section>
 <section className={panel}><h2 className="font-serif text-2xl">Equipment pre-check</h2>{equipment.map(e=><div className="mt-3" key={e.equipment_id}><p className="font-semibold">{e.name}</p>{e.safety_precheck&&<label className="mt-2 flex gap-3 rounded-lg bg-amber-50 p-3 text-sm"><input disabled={!!instance} type="checkbox" checked={!!checks[e.equipment_id]} onChange={v=>setChecks({...checks,[e.equipment_id]:v.target.checked})}/>{e.safety_precheck}</label>}</div>)}</section>
 <details className={panel}><summary className="font-semibold">Dependency graph · {plan.steps.length} actions · {critical.minutes} min critical path</summary><ol className="mt-3 space-y-2 text-sm">{plan.steps.map(s=><li key={s.step_id}><strong>{bundle.cooking.find(t=>t.technique_id===s.technique_id)!.name}</strong> · {s.recipe_name} · {s.duration_min} min {s.attention_type}<div className="text-[#736e65]">← {s.depends_on.length?s.depends_on.map(d=>bundle.cooking.find(t=>t.technique_id===plan.steps.find(x=>x.step_id===d)!.technique_id)!.name).join(' + '):'Ready from the start'}</div></li>)}</ol></details>
 {!instance&&<section className={panel}>{!eligible&&<label className="mb-3 block">Schedule cooking start <input aria-label="Scheduled cooking start" type="datetime-local" value={scheduled} onChange={e=>setScheduled(e.target.value)} className="ml-2 rounded border p-2"/></label>}<button className={button} disabled={!safe||(!eligible&&!scheduled)} onClick={begin}>{eligible?'Start cooking':'Create planned session'}</button>{!safe&&<p className="mt-2 text-sm text-amber-800">Complete the mandatory equipment check to continue.</p>}</section>}</>}
 {view==='cook'&&instance&&<><section className={panel}><h2 className="font-serif text-2xl">{complete?'Ready to serve':recipe.name}</h2><p className="mt-2 text-sm">{instance.entry_mode} session · {new Date(instance.scheduled_for).toLocaleString()} · {plan.steps.filter(s=>instance.step_state[s.step_id]?.done).length}/{plan.steps.length} complete</p><p className="text-sm text-[#736e65]">Progress is saved for this account in this browser. {pending.minutes} min remaining critical path estimate.</p><button className="mt-3 text-sm underline" onClick={()=>{setInstance(null);setChecks({});try{localStorage.removeItem(storageKey)}catch{}setView('review')}}>{complete?'Cook again':'End session and review again'}</button></section>
 {plan.steps.filter(s=>!instance.step_state[s.step_id]?.done).sort((a,b)=>pending.priority[b.step_id]-pending.priority[a.step_id]).map((s,index)=>{const running=!!instance.step_state[s.step_id]?.started_at,ready=canStart(s,plan.steps,instance),tech=bundle.cooking.find(t=>t.technique_id===s.technique_id)!;return <article key={s.step_id} className={panel+(!ready&&!running?' opacity-60':'')}><p className="text-xs uppercase tracking-wider text-[#f4510b]">{s.recipe_name} · {s.attention_type} · {s.duration_min} min {index===0&&ready?'· Start this first':''}</p><h3 className="mt-2 font-serif text-xl">{tech.name}</h3>{(running||ready)&&<><p className="mt-2">{tech.generic_steps[0]}</p><p className="my-2 text-sm font-semibold">Look for: {tech.doneness_signal}</p><p className="text-sm">{s.qty_used.map(u=>`${amount(u.qty)} ${u.unit} ${bundle.identities.find(i=>i.ingredient_id===u.ingredient_id)!.canonical_name}`).join(' · ')}</p><details className="my-3 text-sm"><summary>Technique & doneness help</summary>{tech.generic_steps.join(' ')} {s.sensory_test_id&&bundle.sensory.find(t=>t.test_id===s.sensory_test_id)!.method}<p>Recovery: {tech.recovery_action}</p></details></>}<button className={button+' mt-3'} disabled={!ready&&!running} onClick={()=>setInstance(current=>transition(current!,plan.steps,s.step_id,running?'done':'start',userId))}>{running?'Doneness checked — complete':ready?'Start action':'Waiting for dependencies / attention / equipment'}</button></article>})}</>}
 </div>
}
