'use client'

import { useState } from 'react'
import Image from 'next/image'
import { isRecipeImage } from '@/lib/recipe-image-policy'

// Recipe photos are generated by the invisible catalogue backfill and saved in
// Supabase before they are reused anywhere in the app. This component only reads
// the saved URL; it never shows a different recipe's fallback image.
export function RecipeImage({
  recipe,
  className = '',
  loading = 'lazy',
}: {
  recipe: any
  regenerate?: boolean
  className?: string
  loading?: 'eager' | 'lazy'
}) {
  const storedUrl = String(recipe?.image_url || '')
  const name = recipe?.name || recipe?.title || 'Recipe'
  const [imageUrl, setImageUrl] = useState(() => isRecipeImage(storedUrl) ? storedUrl : '')

  if (!imageUrl) {
    return (
      <div
        className={`block ${className} animate-pulse bg-[#e8e4db]`}
        role="status"
        aria-label={`Recipe photo is being prepared for ${name}`}
      />
    )
  }

  const optimizable =
    imageUrl.startsWith('/') ||
    imageUrl.startsWith('https://www.themealdb.com/images/media/meals/') ||
    imageUrl.startsWith('https://ohnwifpgdoimydddjiwa.supabase.co/storage/v1/object/public/recipe-images/')

  if (!optimizable) {
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img
        src={imageUrl}
        alt={name}
        className={`block ${className}`}
        loading={loading}
        decoding="async"
        onError={() => setImageUrl('')}
      />
    )
  }

  return (
    <Image
      src={imageUrl}
      alt={name}
      width={640}
      height={480}
      sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
      className={`block ${className}`}
      loading={loading}
      onError={() => setImageUrl('')}
    />
  )
}
