import type { RecipeItem } from '@/components/cooking-assistant-app'

export const DEFAULT_RECIPES: RecipeItem[] = [
  {
    id: 'default-poha',
    name: 'Poha',
    title: 'Poha',
    description: 'Light flattened rice with onions, peas, lemon, and fresh coriander.',
    image_url: null,
    meal_type: 'breakfast',
    category: 'Breakfast',
    cuisine: 'Indian',
    diet_type: 'Vegetarian',
    difficulty: 'Easy',
    prep_time: 10,
    cook_time: 15,
    total_time: 25,
    servings: 4,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'default-rajma-masala',
    name: 'Rajma Masala',
    title: 'Rajma Masala',
    description: 'Slow-simmered kidney beans in a rich tomato and warming spice gravy.',
    image_url: null,
    meal_type: 'lunch',
    category: 'Lunch',
    cuisine: 'North Indian',
    diet_type: 'Vegetarian',
    difficulty: 'Easy',
    prep_time: 15,
    cook_time: 35,
    total_time: 50,
    servings: 4,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'default-masala-chai-pakoras',
    name: 'Masala Chai & Pakoras',
    title: 'Masala Chai & Pakoras',
    description: 'Spiced milk tea paired with crisp, golden vegetable fritters.',
    image_url: null,
    meal_type: 'high_tea',
    category: 'High Tea',
    cuisine: 'Indian',
    diet_type: 'Vegetarian',
    difficulty: 'Easy',
    prep_time: 10,
    cook_time: 20,
    total_time: 30,
    servings: 4,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'default-palak-paneer',
    name: 'Palak Paneer',
    title: 'Palak Paneer',
    description: 'Tender paneer in a silky spinach gravy finished with fragrant spices.',
    image_url: null,
    meal_type: 'dinner',
    category: 'Dinner',
    cuisine: 'North Indian',
    diet_type: 'Vegetarian',
    difficulty: 'Easy',
    prep_time: 15,
    cook_time: 25,
    total_time: 40,
    servings: 4,
    ingredients: [],
    instructions: [],
  },
]

export function withDefaultRecipes(recipes: RecipeItem[]): RecipeItem[] {
  const byMealType = new Map(recipes.map((recipe) => [recipe.meal_type, recipe]))
  return DEFAULT_RECIPES.map((fallback) => byMealType.get(fallback.meal_type) || fallback)
}
